// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJctKdgEA98lDQKzVKsJdepFfmwnM1r6Q',
    appId: '1:90571745984:web:198968011ed30a26f01b25',
    messagingSenderId: '90571745984',
    projectId: 'instgram-clone-2e7e9',
    authDomain: 'instgram-clone-2e7e9.firebaseapp.com',
    storageBucket: 'instgram-clone-2e7e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5f1RKu3uauPCW-AJcER38ZygLe7OqvMk',
    appId: '1:90571745984:android:fc86e04bac05b764f01b25',
    messagingSenderId: '90571745984',
    projectId: 'instgram-clone-2e7e9',
    storageBucket: 'instgram-clone-2e7e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjaLCEwrtLEH7sCorc6_XFCo6cQeD_edA',
    appId: '1:90571745984:ios:90194ee2f6de6417f01b25',
    messagingSenderId: '90571745984',
    projectId: 'instgram-clone-2e7e9',
    storageBucket: 'instgram-clone-2e7e9.appspot.com',
    iosClientId: '90571745984-110br9sp07jmbgdeve8348d8gpdulpa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjaLCEwrtLEH7sCorc6_XFCo6cQeD_edA',
    appId: '1:90571745984:ios:90194ee2f6de6417f01b25',
    messagingSenderId: '90571745984',
    projectId: 'instgram-clone-2e7e9',
    storageBucket: 'instgram-clone-2e7e9.appspot.com',
    iosClientId: '90571745984-110br9sp07jmbgdeve8348d8gpdulpa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgramClone',
  );
}
